### ISSUE TITLE
Lack of initial CLI implementation

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-rs#110]
Should support RPC endpoint continuous and the special script mode for qualified users with the extended functionality.

It is also necessary to provide a standard way of distribution through cargo - `cargo install emerald`.

**Comment by sjmackenzie** [comment]
@dulanov can you please clarify these points using examples.

for example the "special script mode" would it look like this:

```
emerald -script "<script>" 
```

What do you want this DSL to do?
Is it not just better to expose the emerald functionality via CLI and programmers can just compose emerald features in bash instead of passing in scripts to emerald to parse? 

Or when you use the word "continuous" do you mean there is a background emerald process keeping RPC connections alive and then a short lived CLI process which'll connect to the background process send the action then immediately die.

I'd imagine the latter would be a better way to go?

**Comment by dulanov** [comment]
@sjm first version without script (DSL), we should release something simple from begining.
