### ISSUE TITLE
Rust-web3?

### ISSUE THREAD

**Issue by rphmeier** [ethereumproject/emerald-rs#2]
Hey, just found this project. It looks pretty similar in goals to https://github.com/tomusdrw/rust-web3.
Maybe we could join efforts on that?

**Comment by rphmeier** [comment]
(to be clear, the goal of a CLI is beyond the scope rust-web3, but that could be quite easily done as a wrapper around the library, re-using the same internals)

**Comment by splix** [comment]
@rphmeier thank you! 

Emerald is actually bigger than just a wrapper, but wrapper is an important part. Unfortunately that project is under LGPL, which is incompatible with our goals. On other hand, maybe authors of that project can reuse our code, we're working on same tech anyway

**Comment by dulanov** [comment]
@rphmeier yes, these projects are very very similar by concept, but in addition to the other licensing model (Apache 2.0 instead of LGPL-3.0) out main point is to borrow all private related things from parity and other clients, for example, wallets, adressbooks, transaction signs, details in [our roadmap](http://www.etcdevteam.com/roadmap.html).
