### ISSUE TITLE
Compile on Ubuntu 16.10 needs additional dependencies

### ISSUE THREAD

**Issue by gagarin55** [ethereumproject/emerald-rs#50]
To compile project on Ubuntu 16.10 you must install `libssl-dev` package. This is not obvious solution so that you can update README or wiki

**Comment by dulanov** [comment]
`libssl-dev` is very similar to mentioned in README.adoc `openssl`.

**Comment by gagarin55** [comment]
No, `openssl` is not enough

**Comment by dulanov** [comment]
Ok, we will return to this problem when we will publish `emerald-rs` as `emerald` crate and will try to reproduce it with `cargo install emerald`.

**Comment by r8d8** [comment]
`openssl` crate tries to run `pkg-config --libs --cflags openssl` and fails because can't find openssl headers.
plain openssl package doesn't not include headers, 
so one should also install them additionaly:
+ Red Hat, Fedora, CentOS - openssl-devel
+ Debian, Ubuntu - libssl-dev
+ Arch - openssl

I think this issue goes solely to `openssl crate` not `emerald` itself
